baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cyiwdio'
theme = "not-much"

[params]
theme = "dark"
palette = "catpuccin"

ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  goldmark = { unsafe = true }

[[menu.main]]
  identifier = "Radio"
  name = "Radio"
  title = "Radio"
  url = "/"

